language: java

jdk:
  - oraclejdk8

dist: trusty

sudo: false

# Caching Gradle
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    #- $HOME/.cache/pip