language: java

jdk:
  - oraclejdk8

dist: trusty

sudo: false

# Install python dependencies in the home directory (no sudo access)
# Transifex-client version 0.12.1 is required
# See https://github.com/transifex/transifex-client/issues/113
install:
  - echo "Installing the Transifex client"
  - pip install --user 'git+https://github.com/eliben/pycparser@release_v2.14'
  - pip install --user 'requests[security]'
  - pip install --user transifex-client
  
# Caching Gradle
before_cache:
  - echo "Cleanin cache."
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    #- $HOME/.cache/pip
script:
  - ./gradlew setupCIWorkspace
  - ./gradlew build