package fle.resource;

import static fle.init.Blocks.dirt;
import static fle.init.Blocks.mineral;
import static fle.init.Blocks.rock;
import static fle.init.Blocks.sand;
import static fle.init.Blocks.stoneChip;

import java.util.Arrays;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLLoadCompleteEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import farcore.util.FleCreativeTab;
import flapi.util.Values;
import fle.core.FLE;
import fle.core.init.IBF;
import fle.resource.block.auto.BlockUniversalDirt;
import fle.resource.block.auto.BlockUniversalMineral;
import fle.resource.block.auto.BlockUniversalRock;
import fle.resource.block.auto.BlockUniversalSand;
import fle.resource.block.auto.BlockUniversalStoneChip;
import net.minecraft.item.Item;

@Mod(modid = FLEResource.MODID, name = FLEResource.NAME, version = FLE.VERSION, dependencies = "required-after:fle@" + FLE.VERSION)
public class FLEResource
{
    public static final String MODID = "fle|resource";
    public static final String NAME = "Far Land Era Resource";
    
    @Instance(MODID)
    public static FLEResource fler;
    
    @SidedProxy(clientSide = "fle.resource.InitClient", serverSide = "fle.resource.Init")
    public static Init init;
    
    public FLEResource()
    {
    	fler = this;
    	FLE.enableLoading(MODID);
	}
    
    @EventHandler
    public void preLoad(FMLPreInitializationEvent event)
    {
        ModMetadata mm = event.getModMetadata();
        mm.credits = "ueyudiud";
        mm.description = "Far tech mod resources, rock, dirt, water, etc.";
        mm.autogenerated = false;
        mm.authorList = Arrays.asList("ueyudiud");
        mm.version = FLE.VERSION;
        mm.url = "http://tieba.baidu.com/p/3977359185";
        mm.logoFile = "/assets/" + Values.TEXTURE_FILE + "/textures/logo.png";
    	init.preLoad();
    }
    
    @EventHandler
    public void load(FMLInitializationEvent event)
    {
    	init.load();
    }

    @EventHandler
    public void postLoad(FMLPostInitializationEvent event)
    {
    	init.postLoad();
    }
    
    @EventHandler
    public void completeLoad(FMLLoadCompleteEvent event)
    {
    	init.completeLoad();
    }
}