package fle.dict;

import java.util.Arrays;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLLoadCompleteEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import flapi.util.Values;
import fle.core.FLE;

@Mod(modid = FLEDictionary.MODID, name = FLEDictionary.NAME, version = FLE.VERSION, dependencies = "required-after:fle@" + FLE.VERSION)
public class FLEDictionary
{
    public static final String MODID = "fle|dictionary";
    public static final String NAME = "Far Land Era Dictionary";

    @Instance(MODID)
    public static FLEDictionary fled;

    @SidedProxy(clientSide = "fle.dict.InitClient", serverSide = "fle.dict.Init")
    public static Init init;
    
    public FLEDictionary()
    {
    	fled = this;
    	FLE.enableLoading(MODID);
	}
    
    @EventHandler
    public void preLoad(FMLPreInitializationEvent event)
    {
        ModMetadata mm = event.getModMetadata();
        mm.credits = "ueyudiud";
        mm.description = "Far tech mod dictionary, provide many kinds of materials.";
        mm.autogenerated = false;
        mm.authorList = Arrays.asList("ueyudiud");
        mm.version = FLE.VERSION;
        mm.url = "http://tieba.baidu.com/p/3977359185";
        mm.logoFile = "/assets/" + Values.TEXTURE_FILE + "/textures/logo.png";
        init.preLoad();
    }
    
    @EventHandler
    public void load(FMLInitializationEvent event)
    {
    	init.load();
    }

    @EventHandler
    public void postLoad(FMLPostInitializationEvent event)
    {
    	init.postLoad();
    }
    
    @EventHandler
    public void completeLoad(FMLLoadCompleteEvent event)
    {
    	init.completeLoad();
    }
}