package fle.machine;

import java.util.Arrays;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLLoadCompleteEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import flapi.util.Values;
import fle.core.FLE;

@Mod(modid = FLEMachine.MODID, name = FLEMachine.NAME, version = FLE.VERSION, dependencies = "required-after:fle@" + FLE.VERSION)
public class FLEMachine
{
    public static final String MODID = "fle|machine";
    public static final String NAME = "Far Land Era Machine";

    @Instance(MODID)
    public static FLEMachine flem;

    @SidedProxy(clientSide = "fle.machine.InitClient", serverSide = "fle.machine.Init")
    public static Init init;
    
    public FLEMachine()
    {
    	flem = this;
    	FLE.enableLoading(MODID);
	}
    
    @EventHandler
    public void preLoad(FMLPreInitializationEvent event)
    {
        ModMetadata mm = event.getModMetadata();
        mm.credits = "ueyudiud";
        mm.description = "Far tech mod machine, provide some default machine (Others see each era child mod).";
        mm.autogenerated = false;
        mm.authorList = Arrays.asList("ueyudiud");
        mm.version = FLE.VERSION;
        mm.url = "http://tieba.baidu.com/p/3977359185";
        mm.logoFile = "/assets/" + Values.TEXTURE_FILE + "/textures/logo.png";
    	init.preLoad();
    }
    
    @EventHandler
    public void load(FMLInitializationEvent event)
    {
    	init.load();
    }

    @EventHandler
    public void postLoad(FMLPostInitializationEvent event)
    {
    	init.postLoad();
    }
    
    @EventHandler
    public void completeLoad(FMLLoadCompleteEvent event)
    {
    	init.completeLoad();
    }
}